cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
     path("add/<int:product_id>/", views.cart_add, name="cart_add"),
     path("remove/<int:product_id>/", views.cart_remove, name="cart_remove"),
     path("", views.cart_detail, name="cart_detail"),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("cart/", include("cart.urls", namespace="cart")),
    path("order/", include("orders.urls", namespace="orders")),
    path("", include("shop.urls", namespace="shop")),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
        )

orders/urls.py
from django.urls import path
from . import views

app_name = "orders"

urlpatterns = [
    path("", views.order_create, name="order_create"),
]

shop/urls.py
from django.urls import path
from . import views

app_name = "shop"

urlpatterns = [
    path("", views.product_list, name="product_list"),
    path(
        "<slug:category_slug>/", views.product_list,
        name="product_list_by_category"
        ),
    path("<int:id>/<slug:slug>/", views.product_detail, name="product_detail"),
]

cart/models.py
from django.db import models

# Create your models here.

orders/models.py
from django.db import models

class Order(models.Model):
    first_name = models.CharField(max_length=50, verbose_name="Имя")
    last_name = models.CharField(max_length=50, verbose_name="Фамилия")
    email = models.EmailField(verbose_name="Э-почта")
    address = models.CharField(max_length=250, verbose_name="Адрес")
    postal_code = models.CharField(
        max_length=20, verbose_name="Почтовый индекс"
        )
    city = models.CharField(max_length=100, verbose_name="Город")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Создан")
    updated = models.DateTimeField(auto_now=True, verbose_name="Обновлён")
    paid = models.BooleanField(default=False, verbose_name="Оплачен")

    class Meta:
        ordering = ["-created"]
        indexes = [models.Index(fields=("-created",)),]
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

    def __str__(self):
        return f"Заказ: {self.id}"
    
    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())
    
class OrderItem(models.Model):
    order = models.ForeignKey(
        Order, related_name="items", on_delete=models.CASCADE,
        verbose_name="Заказ"
        )
    product = models.ForeignKey(
        "shop.Product", related_name="order_items", on_delete=models.CASCADE,
        verbose_name="Товар"
    )
    price = models.DecimalField(
        max_digits=10, decimal_places=2, verbose_name="Цена"
        )
    quantity = models.PositiveIntegerField(default=1, verbose_name="Количество")

    def __str__(self):
        return f"{self.id}"
    
    def get_cost(self):
        return self.price * self.quantity

shop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name="Категория")
    slug = models.SlugField(max_length=255, unique=True) # Уникальность создаёт индексы

    class Meta:
        ordering = ("name",)
        indexes = (models.Index(fields=("name",)),)
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def get_absolute_url(self):
        return reverse(
            "shop:product_list_by_category", kwargs={"category_slug": self.slug}
            )
    

    def __str__(self):
        return f"{self.name}"
    
class Product(models.Model):
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name="products",
        verbose_name="Категория"
        )
    name = models.CharField(max_length=255, verbose_name="Название")
    slug = models.SlugField(max_length=255)
    description = models.TextField(blank=True, verbose_name="Описание")
    image = models.ImageField(
        upload_to="products/%Y/%m/%d", blank=True, verbose_name="Изображение"
        )
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True, verbose_name="Доступность")
    created = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата создания"
        )
    updated = models.DateTimeField(auto_now=True, verbose_name="Дата обновления")

    class Meta:
        ordering = ("name",)
        indexes = (
            models.Index(fields=("id", "slug")),
            models.Index(fields=("name",)),
            models.Index(fields=("-created",)),
            )
        verbose_name = "Товар"
        verbose_name_plural = "Товары"
    
    def get_absolute_url(self):
        return reverse(
            "shop:product_detail", kwargs={"id": self.id, "slug": self.slug}
            )
    

    def __str__(self):
        return f"{self.name}"

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CardAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int
    )
    override = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput
        )

orders/forms.py
from django import forms
from .models import Order

class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            "first_name", "last_name", "email", "address", "postal_code", "city"
        ]

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CardAddProductForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CardAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product, cd["quantity"], cd["override"])
    return redirect("cart:cart_detail")

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect("cart:cart_detail")

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item["update_quantity_form"] = CardAddProductForm(
            initial={"quantity": item["quantity"],
                     "override": True}
        )
    return render(request, "cart/detail.html", {"cart": cart})

orders/views.py
from django.shortcuts import render
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart
from .tasks import order_created

def order_create(request):
    cart = Cart(request)
    if request.method == "POST":
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(
                    order=order, product=item["product"], price=item["price"],
                    quantity=item["quantity"]
                )
            cart.clear()
            # Асинхронная задача
            order_created.delay(order.id)
            return render(request, "orders/created.html", {"order": order})
    else:
        form = OrderCreateForm()
    return render(request, "orders/create.html", {"form": form})

shop/views.py
from unicodedata import category
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CardAddProductForm

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(
        request, "shop/list.html", 
        {"products": products, "category": category, "categories": categories}
        )

def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CardAddProductForm()
    return render(
        request, "shop/detail.html",
        {"product": product, "cart_product_form": cart_product_form}
        )

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>{% block title %}Online Shop{% endblock %}</title>

  <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
  <div id="header">
    <a href="/" class="logo">My shop</a>
  </div>
  <div id="subheader">
    <div class="cart">
      {% with total_items=cart|length %}
        {% if total_items > 0 %}
          Корзина:
          <a href="{% url "cart:cart_detail" %}">
            {{ total_items }} шт.
            ${{ cart.get_total_price }}
          </a>
        {% elif not order %}
          Корзина пуста
        {% endif %}
      {% endwith %}
    </div>
  </div>

  <div id="content">
    {% block content %}
    <!-- Page content goes here -->
    {% endblock %}
  </div>
  {% comment %} <script src="{% static 'js/main.js' %}"></script> {% endcomment %}
  {% comment %} {% block extra_js %}{% endblock %} {% endcomment %}
</body>
</html>

templates/cart/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Моя корзина{% endblock title %}

{% block content %}
<h1>Моя корзина</h1>
<table class="cart">
  <thead>
    <tr>
      <th>Изображение</th>
      <th>Товар</th>
      <th>Количество</th>
      <th>Удалить</th>
      <th>Цена за единицу</th>
      <th>Цена</th>
    </tr>
  </thead>
  <tbody>
    {% for item in cart %}
      {% with product=item.product %}
        <tr>
          <td>
            <a href="{{ product.get_absolute_url }}">
              <img src="{% if product.image %}{{ product.image.url }}
              {% else %}{% static "img/no_image.png" %}{% endif %}" alt="No">
            </a>
          </td>
          <td>{{ product.name }}</td>
          <td>
            <form action="{% url "cart:cart_add" product.id %}" method="post">
              {{ item.update_quantity_form.quantity }}
              {{ item.update_quantity_form.override }}
              {% csrf_token %}
              <input type="submit" value="Обновить">
            </form>
          </td>
          <td>
            <form action="{% url "cart:cart_remove" product.id %}" method="post">
              <input type="submit" value="Remove">
              {% csrf_token %}
            </form>
          </td>
          <td>{{ item.price }}</td>
          <td>{{ item.total_price }}</td>
        </tr >
      {% endwith %}
    {% endfor %}
    <tr>
      <td>Итого</td>
      <td colspan="4"></td>
      <td class="num">${{ cart.get_total_price }}</td>
    </tr>
  </tbody>
</table>
<p class="text-right">
  <a href="{% url "shop:product_list" %}" class="button light">
    Продолжить покупки
  </a>
  <a href="{% url "orders:order_create" %}" class="button">Купить</a>
</p>
{% endblock content %}

templates/orders/create.html
{% extends "base.html" %}

{% block title %}Оформление покупки{% endblock title %}

{% block content %}
  <h1>Оформление покупки</h1>
  <div class="order-info">
    <h3>Ваш заказ</h3>
    <ul>
      {% for item in cart %}
        <li>
          {{ item.quantity }}x {{ item.product.name }}
          <span>${{ item.total_price }}</span>
        </li>
      {% endfor %}
    </ul>
  </div>
  <form method="post" class="order-form">
    {{ form.as_p }}
    <input type="submit" value="Оформить заказ">
    {% csrf_token %}
  </form>
{% endblock content %}

templates/orders/created.html
{% extends "base.html" %}

{% block title %}Заказ оформлен{% endblock title %}

{% block content %}
  <h1>Благодарим за заказ.</h1>
  <p>
    Ваш заказ успешно создан.
    Номер вашего заказа - <strong>{{ order.id }}</strong>.
  </p>
{% endblock content %}

templates/shop/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Страница {{ product.name }}{% endblock title %}

{% block content %}
  <div class="product-detail">
    <img
    src="{% if product.image %}{{ product.image.url }}{% else %}
    {% static "img/no_image.png" %}{% endif %}" alt="No image">
  </div>
  <h1>{{ product.name }}</h1>
  <h2>
    <a href="{{ product.category.get_absolute_url }}">
      {{ product.category }}
    </a>
  </h2>
  <p class="price">{{ product.price }}</p>
  <form action="{% url "cart:cart_add" product.id %}" method="post">
    {{ cart_product_form }}
    {% csrf_token %}
    <input type="submit" value="Добавить в корзину">
  </form>
  {{ product.description | linebreaks }}
{% endblock content %}

templates/shop/list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
{% if category %}{{ category.name }}{% else %}Товары{% endif %}
{% endblock title %}

{% block content %}
  <div id="sidebar">  
    <h3>Категории</h3>
    <ul>
      <li {% if not category %}class="selected"{% endif %}>
        <a href="{% url "shop:product_list" %}">Все</a>
      </li>
      {% for c in categories %}
        <li {% if category.slug == c.slug %}class="selected"{% endif %}>
          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
  <div id="main" class="product-list">
      <h1>{% if category %}{{ category.name }}{% else %}Товары{% endif %}</h1>
      {% for product in products %}
        <div class="item">
          <a href="{{ product.get_absolute_url }}">
            <img src="{% if product.image %}{{product.image.url }}{% else %}
            {% static "img/no_image.png" %}{% endif %}" alt="Фото тавара">
          </a>
          <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
          <br>
          ${{ product.price }}
        </div>
      {% endfor %}
  </div>
{% endblock content %}